//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigerSportLibrary.DB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orderDetail()
        {
            this.player = new HashSet<player>();
        }
    
        public int orderDetailId { get; set; }
        public int orderNumber { get; set; }
        public int style { get; set; }
        public string frontWord { get; set; }
        public Nullable<int> frontWordSize { get; set; }
        public string backWord { get; set; }
        public Nullable<int> backWordSize { get; set; }
        public Nullable<int> chineseFont { get; set; }
        public Nullable<int> englishFont { get; set; }
        public Nullable<int> numberFont { get; set; }
        public int fontColor { get; set; }
        public int quantity { get; set; }
        public Nullable<double> discount { get; set; }
        public string img { get; set; }
        public bool playerName { get; set; }
    
        public virtual chineseFont chineseFont1 { get; set; }
        public virtual engilshFont engilshFont { get; set; }
        public virtual fontColor fontColor1 { get; set; }
        public virtual numberFont numberFont1 { get; set; }
        public virtual order order { get; set; }
        public virtual style style1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player> player { get; set; }
    }
}
